config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations',
    sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password'
    patch 'users/update_password', to: 'users/registrations#update_password'
    post 'users/sign_up/confirm', to: 'users/registrations#confirm_new'
  end

  controller :pages do
    root 'pages#home'
    get '/term', to: 'pages#term'
  end

  controller :users do
    resources :users, only: [:show] do
      member do
        get :following, :followers, :iines
      end
    end
  end

  controller :posts do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:create]
    end
  end

  controller :likes do
    resources :likes, only: [:create, :destroy]
  end

  controller :relationships do
    resources :relationships, only: [:create, :destroy]
  end

  controller :notifications do
    resources :notifications, only: [:index, :update]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  counter_culture :user
  # リレーションーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  # ユーザー
  belongs_to :user

  # 画像
  has_one_attached :image, dependent: :destroy

  # コメント
  has_many :comments, dependent: :destroy

  # いいね
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user

  # 通知
  has_many :notifications, dependent: :destroy

  # バリデーションーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  validates :user_id, presence: true

  # 内容
  validates :content, presence: true, length: { maximum: 250 }

  # 画像
  validates :image,
            presence: true,
            content_type: {
              in: %w(image/jpeg image/png),
              message: "のファイル形式が有効ではありません。",
            },
            size: {
              less_than: 5.megabytes, message: "のファイルサイズは5MB未満です。",
            }

  # メソッドーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
  # 表示用にリサイズした画像を返す
  def display_image
    image.variant(resize_to_fill: [600, 600]).processed
  end

  # 通知機能 CommentとLikeの親モデルであるPostに作成
  # お気に入り通知の作成
  def create_notification_like(current_user)
    # 対象を検索
    temp = Notification.where([
      "visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
      current_user.id, user_id, id, "like",
    ])
    # 対象が存在しなければ、通知を作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: user_id,
        post_id: id,
        action: "like"
      )
      # 自分の投稿に対しては通知済みと処理する
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメント通知の作成
  # コメントは同じ投稿に複数できるので、複数回呼び出せるようにする
  def save_notification_comment(current_user, comment_id, visited_id)
    # コメントの有無による条件分岐はなし
    notification = current_user.active_notifications.new(
      visited_id: visited_id,
      post_id: id,
      comment_id: comment_id,
      action: "comment"
    )
    # 自分の投稿に対しては通知済みと処理する
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def create_notification_post(current_user)
    followers = current_user.followers.ids
    followers.each do |follower|
      save_notification_post(current_user, follower)
    end
  end

  def save_notification_post(current_user, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: visited_id,
      action: "post"
    )
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in_required
  before_action :correct_user, only: :destroy

  def index
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      @post.create_notification_post(current_user)
      flash[:notice] = "投稿が完了しました。"
      redirect_to user_url(current_user)
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = @post.comments.build
    @comments = @post.comments.includes(
      [:user],
      [user: [avatar_attachment: [:blob]]]
    )
  end

  def destroy
    @post.destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to user_url(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end

  # ユーザー確認
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to current_user if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.slim
- if current_page?(posts_path)
  - post = search_post
- user = post.user
li id="post-#{post.id}"
  / モーダルトリガー
  span.bl_modal_trigger type="button" data-toggle="modal" data-target="#post-modal#{post.id}"
    = image_tag post.display_image

  / モーダルターゲット
  .modal.fade id="post-modal#{post.id}" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true"
    / 実際に表示されるモーダル
    .modal-dialog.modal-dialog-centered.modal-lg role="document"
      .modal-content
        .modal-body.d-flex.bl_modal_userBody
          / 投稿画像
          .bl_modal_image
            = link_to post_path(post) do
              = image_tag post.display_image
          / 投稿情報
          .bl_modal_info
            .modal-header.bl_modal_header
              .bl_modal_userInfo
                / アバター
                .bl_avatar
                  = render partial: "shared/avatar_icon", locals: { user: user }
                  p.small
                    = post.created_at.to_s(:datetime_jp)
              .bl_modal_postCont
                p= post.content
            / コメント一覧
            .modal-body.bl_modal_comment.d-none.d-lg-block
              - if post.comments.any?
                ol
                  = render partial: "comments/comment", collection: post.comments, as: :comment
              - else
                p コメントはありません。
            / 個別ページへリンク
            .modal-footer.bl_modal_footer
              .bl_modal_frend.d-lg-flex.pt-5.pt-lg-0
                - unless current_user?(user)
                  = render "likes/like_form", post: post
                = link_to post_path(post) do
                  button.btn.btn-info.rounded-pill.mt-2.mt-lg-0
                    | コメントする
                - if current_user?(user)
                  = button_to "投稿を削除する", post_path(post), data: { confirm: "投稿を削除をしてよろしいですか?" }, method: :delete, class: "btn btn-danger rounded-pill"

app/views/posts/index.html.slim
- provide(:title, '検索結果')
/ 空欄検索の判定
- if params[:q] &.reject { |key, value| value.blank? }.present?
  / 検索ワード該当なし
  - if @search_posts.count == 0
    p= "検索結果 #{@search_posts.count} 件"
    strong= "『#{params[:q][:content_cont]}』"
    span に一致する投稿はありませんでした。
  / 検索ワード該当あり
  - else
    h3= "『#{params[:q][:content_cont]}』"
    p= "検索結果 #{@search_posts.count} 件"
  ol.posts.bl_user_grid
    = render partial: "posts/post", collection: @search_posts, as: :search_post
  .bl_pagination
    = will_paginate @search_posts
- else
  p キーワードを入力してください。

app/views/posts/new.html.slim
- provide(:title, '新規投稿')
.card.col-md-8.mt-5.mx-auto.px-0
  .card-header
    h2 新規投稿
  = form_with model: @post, local: true do |f|
    = render "shared/error_messages", object: f.object
    .field
      label
        img#img_prev.card-img-top src="https://placehold.jp/618x618.png?text=画像を選択" height=618
        = f.file_field :image, accept: "image/jpeg,image/png", id: "post_img", class: 'hidden_file hp_input_none'
    .card-body
      .field
        = f.text_area :content, autocomplete: "content", class: "form-control", size: "5x5", placeholder: "コメントを入力..."
      .actions
        = f.submit "投稿する", class: "btn btn-primary btn-block mt-4"
      = link_to "キャンセルして戻る", user_path(current_user), class: "btn btn-secondary btn-block mt-2"

app/views/posts/show.html.slim
- provide(:title, "#{@post.content}")
.card.col-md-8.mt-5.mx-auto.px-0
  = render partial: "shared/post_unit",
    locals: { user: @user, post: @post, comments: @comments, comment: @comment }