config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations',
    sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords',
    unlocks: 'users/unlocks',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password'
    patch 'users/update_password', to: 'users/registrations#update_password'
    post 'users/sign_up/confirm', to: 'users/registrations#confirm_new'
  end

  controller :pages do
    root 'pages#home'
    get '/term', to: 'pages#term'
  end

  controller :users do
    resources :users, only: [:show] do
      member do
        get :following, :followers, :iines
      end
    end
  end

  controller :posts do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:create]
    end
  end

  controller :likes do
    resources :likes, only: [:create, :destroy]
  end

  controller :relationships do
    resources :relationships, only: [:create, :destroy]
  end

  controller :notifications do
    resources :notifications, only: [:index, :update]
  end
end

app/views/layouts/_footer.html.slim
footer
  nav.navbar.bg-dark.fixed-bottom
    .container
      p 2020 Created by Ash
      = link_to "利用規約", term_path

app/views/layouts/_header.html.slim
header.ly_header
  nav.navbar.fixed-top.navbar-expand-lg.bg-white.navbar-light
    .container
      / ロゴ
      h1= link_to "インスタ！", root_path, class: "navbar-brand el_lv1Heading logo"
      - if user_signed_in?
        / ハンバーガートリガー
        button.navbar-toggler type="button" data-toggle="collapse" data-target="#change-nav" aria-controls="change-nav" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon

        / ハンバーガー 対象
        .collapse.navbar-collapse#change-nav
          .m-auto
            / 検索
            dl.bl_search.mt-2
              / 何故か空フォームを二重に置かなければ動かない
              = search_form_for @search, url: posts_path do |f|
              = search_form_for @search, url: posts_path do |f|
                dt.bl_search_field
                  = f.text_field :content_cont, placeholder: "キーワード検索"
                dd.bl_search_btn
                  = f.submit "検索"
          / ナビアイコン
          ul.navbar-nav
            li.nav-item.mr-4
              = link_to notifications_path, class: "nav-link" do
                - if unchecked_notifications.any?
                  span.fa-stack
                    i.far.fa-bell.d-none.d-lg-block.fa-stack-2x
                    i.fas.fa-circle.n-circle.fa-stack-1x.d-none.d-lg-block
                  span.d-lg-none.d-block お知らせ
                - else
                  i.far.fa-bell.hp_aweIcon.d-none.d-lg-block
                  i.d-lg-none.d-block お知らせ
            li.nav-item.mr-4
              = link_to new_post_path, class: "nav-link"
                span.far.fa-images.hp_aweIcon.d-none.d-lg-block
                span.d-lg-none.d-block 投稿する
            li.nav-item.mr-4
              = link_to current_user, class: "nav-link"
                span.far.fa-user.hp_aweIcon.d-none.d-lg-block
                span.d-lg-none.d-block マイページ
            li.nav-item
              = link_to destroy_user_session_path, method: :delete, class: "nav-link"
                span.fas.fa-sign-out-alt.hp_aweIcon.d-none.d-lg-block
                span.d-lg-none.d-block ログアウト

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= csp_meta_tag
= favicon_link_tag('favicon.ico')
meta name="description" content="画像投稿サイト「Insta!」は、投稿した画像を通してユーザーとの共有を楽しむサイトです。"
= analytics_init if Rails.env.production?
= stylesheet_link_tag "https://unpkg.com/swiper/swiper-bundle.css"
= javascript_include_tag "https://unpkg.com/swiper/swiper-bundle.js"
= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    title= full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |flash_key, flash_message|
        - next if flash_key == 'timedout'
        = content_tag(:div, flash_message, class: "alert alert-#{ flash_key == "notice" ? "success" : "danger"}")
      = yield
    = render 'layouts/footer'